#!/bin/bash

#scripts/bootstrap.sh
# Sudo upfront
if [ "$(id -u)" != "0" ]; then
	echo "Please run as Sudo"
	exit 1
fi

# Keep sudo alive
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Brew Install
#sudo ./brew/install.sh

# NPM Install
#sudo ./npm/install.sh

# Bootstrap Install
#sudo ./scripts/bootstrap.sh
