#!/bin/bash

#scripts/bootstrap.sh
# Sudo upfront

if [ "$(id -u)" != "0" ]; then
	echo "please supply sudo password"
	exit 1
fi

# Keep sudo alive
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

#sudo ./scripts/whichOS.sh

sudo ./scripts/bootstrap.sh
