" ================================================

" PATHOGEN

execute pathogen#infect()

" ================================================

set laststatus=2 " hopefully a fix for airline

set nohlsearch

set backspace=indent,eol,start

"autocmd VimEnter * NERDTree

set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
Plugin 'tpope/vim-fugitive'
" plugin from http://vim-scripts.org/vim/scripts.html
Plugin 'L9'
" Git plugin not hosted on GitHub
Plugin 'git://git.wincent.com/command-t.git'
" git repos on your local machine (i.e. when working on your own plugin)
Plugin 'file:///home/gmarik/path/to/plugin'
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" Avoid a name conflict with L9
Plugin 'user/L9', {'name': 'newL9'}

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

set shell=/bin/sh

let g:ycm_global_ycm_extra_conf = '~/.ycm_extra_conf.py'                      
let g:ycm_confirm_extra_conf = 0

set runtimepath^=~/.vim/bundle/ctrlp.vim

let g:ctrlp_map = '<c-p>'


nnoremap <CR> :noh<CR><CR>
" Maps NerdTree to ,ne
let mapleader = ","
nmap <leader>ne :NERDTree<cr>

" Maps :wq to cntrl s
inoremap <C-s> <esc>:w<cr>a
nnoremap <C-s> :w<cr>

colorscheme molokai" awesome colorscheme
"let g:molokai_original = 1 "original colors
let g:rehash256 = 1

" In order to install more color schemes move the colorscheme.vim file to colors
" and change the name above

syntax enable " enable syntax processing

set tabstop=4 " number of visual spaces per tab space

set softtabstop=4 "number of spaces in tab when editing

set expandtab " tabs are spaces

" tab now becomes a shortcut for inserting four spaces per tab

set number "show line numbers

set showcmd "show command in bottom bar / shows last command entered
" in the bottom right vim

set cursorline " highlight current line

filetype indent on " load filetupe-specific indent files

" if a /.vim/indent/filetype.vim gets made it will load that specific type

"set wildmenu " visual autcomplete for command menu

set lazyredraw " redraw only when needed

set showmatch "highlight matching [{()}]

set incsearch "search as characters are entered

set hlsearch "highlights the matches

" Turn off search highlight
" Turns off when ,<space>
nnoremap <leader><space> :nohlsearch<CR> 

set foldenable " enable folding

set foldlevelstart=10 "open most folds by default

set foldnestmax=10 "10 nested fold max

"space open/closes folds
nnoremap <space> za

set foldmethod=indent " fold based on indent level

au BufNewFile,BufRead *.handlebars set filetype=html
