#!usr/bin/env bash

sudo -v

while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# upgrade machine
apt-get update
apt-get dist-upgrade

# Setup sources.list
sh -c 'echo "deb http://packages.ros.org/ros/ubuntu trusty main" > /etc/apt/sources.list.d/ros-latest.list'

# Set up keys
wget https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -O - | sudo apt-key add -

# make sure up to date
apt-get update

# Install desktop
apt-get install ros-indigo-desktop-full

#initialize rosdep
rosdep init
rosdep update

#Environment Setup
echo "source /opt/ros/indigo/setup.bash" >> ~/.bashrc
source ~/.bashrc

# Get Rosinstall
apt-get install python-rosinstall