#!/bin/bash

sudo -v


# upgrade machine
sudo apt-get update
sudo apt-get dist-upgrade

# Setup sources.list
sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu trusty main" > /etc/apt/sources.list.d/ros-latest.list'

# Set up keys
wget https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -O - | sudo apt-key add -

# make sure up to date
sudo apt-get update

# Install desktop
sudo apt-get install -y ros-indigo-desktop-full

#initialize rosdep
sudo rosdep init
rosdep update

#Environment Setup
echo "source /opt/ros/indigo/setup.bash" >> ~/.bashrc
source ~/.bashrc

# Get Rosinstall
sudo apt-get install -y python-rosinstall